FROM kalilinux/kali-linux-docker

RUN apt update -y \
  && apt install -y curl gnupg apt-transport-https \
  && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | tee /etc/apt/sources.list.d/azure-cli.list \
  && curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && apt update -y \
  #&& apt -o Dpkg::Progress-Fancy="0"  dist-upgrade -y \
  #&& apt -o Dpkg::Progress-Fancy="0" install -y linux-image-4.16.0-kali2-cloud-amd64 \
  #&& apt install -y azure-cli \
  #&& /usr/bin/msfdb init \
  && apt -y autoremove